import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Use — Gintex AI",
  description:
    "Read the Terms of Use governing your access to the Gintex AI website and perception intelligence services.",
  alternates: { canonical: "https://www.gintex.ai/terms-of-use" },
};

const SECTIONS = [
  {
    id: "acceptance",
    title: "1. Acceptance of Terms",
    content: (
      <>
        <p>
          These Terms of Use ("Terms") govern your access to and use of the
          website located at <strong>www.gintex.ai</strong> (the "Site"),
          operated by Gintex AI ("Gintex", "we", "us", or "our"), as well as
          any associated services, content, or features (collectively, the
          "Services").
        </p>
        <p>
          By accessing or using the Site, you agree to be bound by these Terms
          and our{" "}
          <a href="/privacy-policy" style={{ color: "var(--accent-cyan)" }}>
            Privacy Policy
          </a>
          , which is incorporated herein by reference. If you do not agree to
          these Terms, please do not use the Site.
        </p>
        <p>
          These Terms apply to all visitors, users, and others who access or
          use the Site ("Users"). Use of the Site constitutes your binding
          acceptance of these Terms, regardless of whether you have read them.
        </p>
      </>
    ),
  },
  {
    id: "description",
    title: "2. Description of Services",
    content: (
      <>
        <p>
          Gintex AI is a <strong>brand perception intelligence platform</strong>{" "}
          that provides:
        </p>
        <ul>
          <li>AI Visibility Intelligence — auditing how AI systems represent your brand</li>
          <li>Reputation and Perception Intelligence — GeoRepute market audits and analysis</li>
          <li>GEO and SEO infrastructure consulting</li>
          <li>Strategic market intelligence reports</li>
          <li>Executive advisory and strategic growth consulting</li>
          <li>Market Execution through the GeoRepute ecosystem</li>
        </ul>
        <p>
          The Site also provides publicly accessible intelligence articles and
          blog content generated by our team, including through AI-assisted
          drafting tools used exclusively by our staff.
        </p>
        <p>
          We reserve the right to modify, suspend, or discontinue any aspect of
          the Services at any time without notice.
        </p>
      </>
    ),
  },
  {
    id: "user-responsibilities",
    title: "3. User Responsibilities",
    content: (
      <>
        <p>By using the Site, you represent and warrant that:</p>
        <ul>
          <li>You are at least 18 years of age or the age of majority in your jurisdiction.</li>
          <li>You have the legal capacity to enter into a binding agreement.</li>
          <li>All information you provide to us (e.g., via the contact form) is accurate, current, and complete.</li>
          <li>You will promptly update any information you provide if it changes.</li>
          <li>Your use of the Site complies with all applicable laws and regulations in your jurisdiction.</li>
        </ul>
      </>
    ),
  },
  {
    id: "account-registration",
    title: "4. Account Registration",
    content: (
      <>
        <p>
          The Site does not offer public user account registration. Admin and
          editor accounts are reserved for authorized Gintex AI personnel only
          and are created and managed internally.
        </p>
        <p>
          Authorized administrators are responsible for maintaining the
          confidentiality of their login credentials and for all activities
          that occur under their account. You agree to notify Gintex AI
          immediately of any unauthorized use of your account or any other
          security breach.
        </p>
        <p>
          Gintex AI reserves the right to terminate admin accounts at any time
          for any reason, including violation of these Terms.
        </p>
      </>
    ),
  },
  {
    id: "acceptable-use",
    title: "5. Acceptable Use",
    content: (
      <>
        <p>You agree not to use the Site to:</p>
        <ul>
          <li>Violate any applicable local, national, or international law or regulation.</li>
          <li>
            Transmit, distribute, or upload any content that is unlawful,
            harmful, defamatory, obscene, fraudulent, or otherwise
            objectionable.
          </li>
          <li>
            Impersonate any person or entity or misrepresent your affiliation
            with any person or entity.
          </li>
          <li>
            Engage in any automated scraping, data mining, or use of bots,
            crawlers, or similar tools to extract content from the Site without
            our prior written consent.
          </li>
          <li>
            Attempt to gain unauthorized access to any part of the Site or its
            related systems, servers, or networks.
          </li>
          <li>
            Interfere with or disrupt the integrity or performance of the Site
            or the data contained therein.
          </li>
          <li>
            Use the Site in any manner that could disable, overburden, or
            impair the Site or our infrastructure.
          </li>
          <li>
            Collect or harvest any personally identifiable information from the
            Site without authorization.
          </li>
          <li>
            Use the Site to transmit unsolicited communications (spam) or
            engage in phishing.
          </li>
        </ul>
        <p>
          Gintex AI reserves the right to investigate and take appropriate
          legal action against any person who, in our sole discretion, violates
          this provision.
        </p>
      </>
    ),
  },
  {
    id: "intellectual-property",
    title: "6. Intellectual Property",
    content: (
      <>
        <p>
          The Site and all of its content — including but not limited to text,
          articles, intelligence reports, graphics, logos, icons, images,
          audio clips, data compilations, and software — are the exclusive
          property of Gintex AI or its content suppliers and are protected by
          applicable copyright, trademark, trade secret, and other intellectual
          property laws.
        </p>
        <p>
          You are granted a limited, non-exclusive, non-transferable,
          revocable license to access and view the Site and its content for
          your personal, non-commercial use only. This license does not include:
        </p>
        <ul>
          <li>Any resale or commercial use of the Site or its content</li>
          <li>Any collection or use of product listings, descriptions, or prices</li>
          <li>Any derivative use of the Site or its content</li>
          <li>Any downloading or copying of account information for the benefit of another party</li>
          <li>
            Any use of data mining, robots, or similar data gathering and
            extraction tools
          </li>
        </ul>
        <p>
          The Gintex AI name, logo, and all related product and service names
          are trademarks of Gintex AI. You may not use these marks without our
          prior written permission.
        </p>
      </>
    ),
  },
  {
    id: "user-content",
    title: "7. User-Submitted Content",
    content: (
      <>
        <p>
          When you submit information through the Site (such as a contact form
          message or consultation request), you grant Gintex AI a
          non-exclusive, worldwide, royalty-free license to use, process, and
          store that information for the purpose of responding to your inquiry
          and delivering our Services.
        </p>
        <p>
          You are solely responsible for the accuracy and legality of any
          content or information you submit. Gintex AI is not responsible for
          any content submitted by users and does not endorse any views
          expressed therein.
        </p>
      </>
    ),
  },
  {
    id: "third-party-links",
    title: "8. Third-Party Links and Services",
    content: (
      <>
        <p>
          The Site may contain links to third-party websites and services,
          including affiliated platforms such as{" "}
          <strong>GeoRepute Intelligence</strong> (georepute.com),{" "}
          <strong>CopyUp</strong> (copyup.io), and{" "}
          <strong>OnlinePerception</strong> (onlineperception.ai), as well as
          social media platforms.
        </p>
        <p>
          These third-party sites have their own terms of use and privacy
          policies. Gintex AI has no control over and assumes no responsibility
          for the content, privacy practices, or terms of any third-party
          websites. We encourage you to review the relevant policies before
          interacting with those sites.
        </p>
        <p>
          Inclusion of a link to a third-party site does not constitute
          endorsement by Gintex AI.
        </p>
      </>
    ),
  },
  {
    id: "service-availability",
    title: "9. Service Availability",
    content: (
      <>
        <p>
          We strive to ensure that the Site is available at all times; however,
          we do not guarantee uninterrupted, error-free access. The Site may
          be unavailable due to maintenance, updates, server outages, or
          circumstances beyond our control.
        </p>
        <p>
          Gintex AI reserves the right to modify, suspend, or permanently
          discontinue the Site or any of its features at any time, with or
          without notice, and without liability to you.
        </p>
      </>
    ),
  },
  {
    id: "disclaimers",
    title: "10. Disclaimer of Warranties",
    content: (
      <>
        <p>
          THE SITE AND ALL CONTENT AND SERVICES PROVIDED THROUGH IT ARE
          PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS WITHOUT WARRANTIES OF
          ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
          IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
          PURPOSE, TITLE, OR NON-INFRINGEMENT.
        </p>
        <p>
          GINTEX AI DOES NOT WARRANT THAT: (A) THE SITE WILL BE UNINTERRUPTED
          OR ERROR-FREE; (B) DEFECTS WILL BE CORRECTED; (C) THE SITE OR ITS
          SERVERS ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS; OR (D) THE
          RESULTS OF USING THE SITE WILL MEET YOUR REQUIREMENTS.
        </p>
        <p>
          Intelligence reports, market analyses, and advisory content provided
          through our Services are based on information available at the time
          of production and represent our professional assessment. They should
          not be construed as legal, financial, or investment advice. Gintex AI
          is not responsible for decisions made based on our analysis.
        </p>
      </>
    ),
  },
  {
    id: "liability",
    title: "11. Limitation of Liability",
    content: (
      <>
        <p>
          TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL
          GINTEX AI, ITS DIRECTORS, EMPLOYEES, PARTNERS, AGENTS, SUPPLIERS, OR
          AFFILIATES BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL,
          CONSEQUENTIAL, OR PUNITIVE DAMAGES — INCLUDING WITHOUT LIMITATION
          LOSS OF PROFITS, DATA, USE, OR GOODWILL — ARISING OUT OF OR IN
          CONNECTION WITH YOUR USE OF, OR INABILITY TO USE, THE SITE OR
          SERVICES, REGARDLESS OF WHETHER SUCH DAMAGES ARE BASED ON CONTRACT,
          TORT, NEGLIGENCE, STRICT LIABILITY, OR ANY OTHER LEGAL THEORY, AND
          EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
        </p>
        <p>
          OUR TOTAL CUMULATIVE LIABILITY TO YOU FOR ALL CLAIMS ARISING FROM OR
          RELATING TO THESE TERMS OR THE SITE SHALL NOT EXCEED THE GREATER OF
          (A) THE AMOUNT YOU PAID US IN THE TWELVE (12) MONTHS PRECEDING THE
          CLAIM, OR (B) ONE HUNDRED US DOLLARS (USD $100).
        </p>
        <p>
          SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF
          CERTAIN DAMAGES, SO THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU.
        </p>
      </>
    ),
  },
  {
    id: "indemnification",
    title: "12. Indemnification",
    content: (
      <>
        <p>
          You agree to defend, indemnify, and hold harmless Gintex AI and its
          affiliates, officers, directors, employees, and agents from and
          against any and all claims, damages, obligations, losses, liabilities,
          costs, or debt, and expenses (including reasonable attorneys' fees)
          arising from: (a) your use of the Site or Services in violation of
          these Terms; (b) any content you submit to the Site; or (c) your
          violation of any third-party rights, including intellectual property
          rights.
        </p>
      </>
    ),
  },
  {
    id: "termination",
    title: "13. Termination",
    content: (
      <>
        <p>
          Gintex AI reserves the right, in its sole discretion, to terminate
          or restrict your access to the Site at any time and for any reason,
          including if we reasonably believe you have violated these Terms.
        </p>
        <p>
          Upon termination, all licenses and rights granted to you under these
          Terms will immediately cease. Provisions of these Terms that by their
          nature should survive termination — including intellectual property,
          disclaimers, indemnification, and limitation of liability — shall
          survive.
        </p>
      </>
    ),
  },
  {
    id: "governing-law",
    title: "14. Governing Law and Dispute Resolution",
    content: (
      <>
        <p>
          These Terms shall be governed by and construed in accordance with the
          laws applicable in the jurisdiction where Gintex AI is registered,
          without regard to its conflict of law provisions.
        </p>
        <p>
          Any dispute arising out of or in connection with these Terms or your
          use of the Site shall first be attempted to be resolved through
          good-faith negotiations. If a resolution cannot be reached within
          30 days, the parties agree to submit to binding arbitration or the
          exclusive jurisdiction of the competent courts in the applicable
          jurisdiction, as determined by Gintex AI.
        </p>
      </>
    ),
  },
  {
    id: "changes",
    title: "15. Changes to Terms",
    content: (
      <>
        <p>
          We reserve the right to modify these Terms at any time. Changes will
          be effective immediately upon posting the updated Terms to this page.
          The "Last Updated" date at the top of this page reflects the date of
          the most recent revision.
        </p>
        <p>
          Your continued use of the Site after any changes to these Terms
          constitutes your acceptance of the revised Terms. If you do not agree
          to the new Terms, you must stop using the Site.
        </p>
      </>
    ),
  },
  {
    id: "contact",
    title: "16. Contact Information",
    content: (
      <>
        <p>
          If you have questions about these Terms of Use, please contact us:
        </p>
        <address className="not-italic leading-loose" style={{ color: "var(--text-secondary)" }}>
          <strong style={{ color: "var(--text-primary)" }}>Gintex AI</strong>
          <br />
          Legal Team
          <br />
          Email:{" "}
          <a href="mailto:Hello@gintex.ai" style={{ color: "var(--accent-cyan)" }}>
            Hello@gintex.ai
          </a>
          <br />
          Website:{" "}
          <a href="https://www.gintex.ai" style={{ color: "var(--accent-cyan)" }}>
            www.gintex.ai
          </a>
        </address>
      </>
    ),
  },
];

export default function TermsOfUsePage() {
  return (
    <main
      className="flex flex-1 flex-col transition-colors duration-300"
      style={{ background: "var(--bg-page)", color: "var(--text-primary)" }}
    >
      {/* Hero */}
      <section
        className="border-b px-6 py-16 sm:px-10 sm:py-20"
        style={{ borderColor: "var(--border)", background: "var(--bg-subtle)" }}
      >
        <div className="mx-auto max-w-3xl">
          <p
            className="mb-3 text-xs font-semibold uppercase tracking-widest"
            style={{ color: "var(--accent-cyan)" }}
          >
            Legal
          </p>
          <h1 className="mb-4 text-4xl font-bold tracking-tight sm:text-5xl">
            Terms of Use
          </h1>
          <p className="text-sm" style={{ color: "var(--text-muted)" }}>
            Last Updated: June 2, 2026
          </p>
          <p className="mt-4 max-w-2xl text-lg leading-relaxed" style={{ color: "var(--text-secondary)" }}>
            Please read these Terms of Use carefully before using the Gintex AI
            website. These Terms constitute a legally binding agreement between
            you and Gintex AI.
          </p>
        </div>
      </section>

      {/* Table of Contents */}
      <section
        className="border-b px-6 py-8 sm:px-10"
        style={{ borderColor: "var(--border)", background: "var(--bg-subtle)" }}
      >
        <div className="mx-auto max-w-3xl">
          <h2
            className="mb-4 text-sm font-semibold uppercase tracking-wider"
            style={{ color: "var(--text-muted)" }}
          >
            Table of Contents
          </h2>
          <ol className="grid grid-cols-1 gap-1 sm:grid-cols-2">
            {SECTIONS.map((s) => (
              <li key={s.id}>
                <a
                  href={`#${s.id}`}
                  className="text-sm transition-colors duration-150"
                  style={{ color: "var(--accent-cyan)" }}
                >
                  {s.title}
                </a>
              </li>
            ))}
          </ol>
        </div>
      </section>

      {/* Content */}
      <section className="px-6 py-12 sm:px-10 sm:py-16">
        <div className="mx-auto max-w-3xl space-y-14">
          {SECTIONS.map((s) => (
            <div key={s.id} id={s.id} className="scroll-mt-24">
              <h2 className="mb-5 text-xl font-bold sm:text-2xl">{s.title}</h2>
              <div
                className="legal-prose space-y-4 text-base leading-relaxed"
                style={{ color: "var(--text-secondary)" }}
              >
                {s.content}
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Footer CTA */}
      <section
        className="border-t px-6 py-12 sm:px-10"
        style={{ borderColor: "var(--border)", background: "var(--bg-subtle)" }}
      >
        <div className="mx-auto max-w-3xl flex flex-col sm:flex-row gap-4 items-center justify-center">
          <a
            href="/privacy-policy"
            className="rounded-full border px-6 py-3 text-sm font-semibold transition-colors duration-200"
            style={{ borderColor: "var(--border)", color: "var(--text-secondary)" }}
          >
            Privacy Policy
          </a>
          <a
            href="/cookie-policy"
            className="rounded-full border px-6 py-3 text-sm font-semibold transition-colors duration-200"
            style={{ borderColor: "var(--border)", color: "var(--text-secondary)" }}
          >
            Cookie Policy
          </a>
          <a
            href="/contact"
            className="rounded-full bg-gradient-to-r from-blue-600 to-purple-600 px-6 py-3 text-sm font-semibold text-white shadow-sm transition-opacity hover:opacity-90"
          >
            Contact Us
          </a>
        </div>
      </section>

      <style>{`
        .legal-prose ul, .legal-prose ol {
          padding-left: 1.5rem;
          display: flex;
          flex-direction: column;
          gap: 0.5rem;
          list-style: disc;
        }
        .legal-prose address {
          margin-top: 0.5rem;
          line-height: 1.8;
        }
      `}</style>
    </main>
  );
}
